# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 664622ee8a986362f9973666047aec76324e9363db056d01163079fbfef8467beb03f3fb1290ace49ad0d63a93a53169ee99097892a50f60af3bdeef63f967f2

test:
  secret_key_base: bd8bd2ed4d6b567540f17fe70ddcdfab331745b94431ccf4807b60705b006c251ebe513e9370e6c0b8e9078c1ce63aa87df5cbf6f81519396852abc03bb957e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
